stage_name = "一部でも"
content = """
WWWWWWWWWWWWWWW
W             W
W      W      W
W   N11111N   W
W      W      W
W             W
WWWWWWWWWWG11GW
        W     W
        W  E  W
        W     W
        WWWWWWW
"""
player_origin = [3, 6]
player_defaultbits = [false, false]
