content = """
WWWWWWWWWWWW
W          W
W          W
W  N0110N  W
W          W
W          W
WWWWWWWG11GW
     W     W
     W  E  W
     W     W
     WWWWWWW
"""
player_origin = [3, 6]
player_defaultbits = [false, false]
