stage_name = "オドロキでひっくり返そう"
content = """
WWWWWWWWWWWWWW
W            W
W   W    W   W
W   WN11NW   W
W   W    W   W
W            W
WWWWWWWWWG11GW
       W     W
       W  E  W
       W     W
       WWWWWWW
"""
player_origin = [3, 6]
player_defaultbits = [false, false]
